name: CI pipeline
on:
    push:
      branches:
        - main
jobs:
    sca:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read 
          actions: read
        steps:
          - name: checkout
            uses: actions/checkout@v4
        
          - name: Depcheck
            uses: dependency-check/Dependency-Check_Action@main
            id: Depcheck
            with:
              project: 'test'
              path: '.'
              format: 'HTML'
              out: 'reports' # this is the default, no need to specify unless you wish to override it
              args: >
                --enableRetired
            #--failOnCVSS 7   # this is the part that breaks the pipeline if a high severity vulnerability is found.
            
          - name: Upload Test results
            if: always()
            uses: actions/upload-artifact@v4
            with:
               name: Depcheck report
               path: ${{github.workspace}}/reports
